# Project identification
sonar.projectKey=sherlock
sonar.projectName=Sherlock
sonar.projectVersion=1.0

# Path to source directories
sonar.sources=sherlock_project
# Path to test directories
sonar.tests=tests

# Language settings
sonar.python.version=3
sonar.sourceEncoding=UTF-8

# Exclusions (optional but recommended)
sonar.exclusions=**/__pycache__/**, **/.venv/**, **/tests/**
