name: Nightly Online Tests

on:
  schedule:
    - cron: '0 3 * * *'
  workflow_dispatch:

jobs:
  online:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          cache: 'pip'
      - run: pip install -e .[dev]
      - run: pytest -q -m online --maxfail=1


